# Site settings
name: Fransiscus Rolanda Malau
title: Fransiscus Rolanda Malau | Web Developer
description: Web Developer focused to build websites & web applications.
url: https://ndomalau.me/
baseurl: ''
email: fransiscusrmalau@gmail.com
cover: https://ndomalau.me/img/og.png
logo: https://ndomalau.me/img/emojis/technologist.png
resume: https://ndomalau.me/resume.pdf
social:
  - title: email
    url: mailto:fransiscusrmalau@gmail.com
  - title: twitter
    url: https://twitter.com/ndomaIau
  - title: github
    url: https://github.com/fransiscusrolandamalau
  - title: linkedin
    url: https://www.linkedin.com/in/fransiscus-rolanda-malau

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
